plugins {
    id 'java'
}

group = 'cc.jlom'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

jar {
    manifest {
        attributes(
                'Main-Class' : 'java/cc/jlom/Main'
        )
    }
}

dependencies {
    implementation 'org.ow2.asm:asm:9.9'
    implementation 'org.ow2.asm:asm-util:9.9'
    implementation 'org.ow2.asm:asm-tree:9.9'

}

test {
    useJUnitPlatform()
}